# Generated by Django 4.2.1 on 2023-05-25 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_rename_nombre_proyectos_titulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('inicio_tiempo', models.DateField()),
                ('fin_tiempo', models.DateField()),
                ('usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('creada', models.DateField(auto_now_add=True)),
                ('importante', models.BooleanField(default=False)),
                ('puntos', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.proyecto')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='usuario_asignado',
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
